// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdkZ5egpnW4iyaLTQmAzgx5IQOWCGlXA0',
    appId: '1:462204121529:android:461306e78f7771bbe54668',
    messagingSenderId: '462204121529',
    projectId: 'final-project-8f199',
    storageBucket: 'final-project-8f199.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbTly7tLaVtQPgKKFmM1NB0pGY3e5Ew0I',
    appId: '1:462204121529:ios:2718d53c961612c9e54668',
    messagingSenderId: '462204121529',
    projectId: 'final-project-8f199',
    storageBucket: 'final-project-8f199.firebasestorage.app',
    iosBundleId: 'com.example.rupaNusa',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9ecsoRdlr3Ap0UBzq4ipHVR45CHVMACM',
    appId: '1:462204121529:web:e56163801a9f9e45e54668',
    messagingSenderId: '462204121529',
    projectId: 'final-project-8f199',
    authDomain: 'final-project-8f199.firebaseapp.com',
    storageBucket: 'final-project-8f199.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbTly7tLaVtQPgKKFmM1NB0pGY3e5Ew0I',
    appId: '1:462204121529:ios:2718d53c961612c9e54668',
    messagingSenderId: '462204121529',
    projectId: 'final-project-8f199',
    storageBucket: 'final-project-8f199.firebasestorage.app',
    iosBundleId: 'com.example.rupaNusa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9ecsoRdlr3Ap0UBzq4ipHVR45CHVMACM',
    appId: '1:462204121529:web:ae35dea25b04a132e54668',
    messagingSenderId: '462204121529',
    projectId: 'final-project-8f199',
    authDomain: 'final-project-8f199.firebaseapp.com',
    storageBucket: 'final-project-8f199.firebasestorage.app',
  );

}